added docker test and verification

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -218,6 +218,55 @@ jobs:
             . || (echo "❌ Failed to build image with tag: $BUILDIMAGE:$BUILDTAG" && exit 1)
           echo "✅ Proxy-Router Test Build of $BUILDIMAGE:$BUILDTAG Successful!"
 
+      - name: Run Docker Image to Test
+        run: |
+          BUILDTAG=${{ needs.Generate-Tag.outputs.tag_name }}
+          BUILDIMAGE=${{ needs.Generate-Tag.outputs.image_name }}
+          docker run -d \
+            -e CLONE_FACTORY_ADDRESS=${{ env.CLONE_FACTORY_ADDRESS }} \
+            -e ETH_NODE_ADDRESS=${{ env.ETH_NODE_ADDRESS }} \
+            -e POOL_ADDRESS=${{ env.POOL_ADDRESS }} \
+            -e WEB_ADDRESS=${{ env.WEB_ADDRESS }} \
+            -e WALLET_PRIVATE_KEY=${{ secrets.WALLET_PRIVATE_KEY }} \
+            -p 8888:8888 \
+            --name proxy-router-test \
+            $BUILDIMAGE:$BUILDTAG || (echo "❌ Failed to run image with tag: $BUILDIMAGE:$BUILDTAG" && exit 0)
+        
+      - name: Perform Version Check
+        if: success()  # This step runs only if the previous step is successful
+        run: |
+          BUILDTAG=${{ needs.Generate-Tag.outputs.tag_name }}
+          BUILDIMAGE=${{ needs.Generate-Tag.outputs.image_name }}
+                 timeout=10
+          while ! curl -s http://localhost:8888/healthcheck >/dev/null; do
+            ((timeout--))
+            if ((timeout <= 0)); then
+              echo "❌ Container failed to start in time"
+              docker logs proxy-router-test
+              exit 0
+            fi
+            sleep 1
+          done
+          echo "✅ Proxy-Router started successfully!"
+          VERSION_TAG=$(curl --silent http://localhost:8888/healthcheck | jq -r '.version')
+          echo "📜 Fetching container logs:"
+          docker logs proxy-router-test
+          if [ "$VERSION_TAG" == "$BUILDTAG" ]; then
+            echo "✅ Version tag in container matches the expected tag: $VERSION_TAG"
+          else
+            echo "❌ Version tag mismatch: Expected $BUILDTAG, but got $VERSION_TAG"
+            exit 0  # Prevent failure and continue
+          fi
+      
+      - name: Stop and Remove Docker Container
+        run: |
+          # Redefine the variables for this step
+          BUILDTAG=${{ needs.Generate-Tag.outputs.tag_name }}
+          BUILDIMAGE=${{ needs.Generate-Tag.outputs.image_name }}
+          docker stop proxy-router-test
+          docker rm proxy-router-test
+          echo "✅ Proxy-Router Test Run of $BUILDIMAGE:$BUILDTAG Successful!"
+
   GHCR-Build-and-Push:
     if: |
       (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'))
