fix port on initial check

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -116,16 +116,16 @@ jobs:
               -e CLONE_FACTORY_ADDRESS=${{ vars.CLONE_FACTORY_ADDRESS }} \
               -e ETH_NODE_ADDRESS=${{ vars.ETH_NODE_ADDRESS }} \
               -e POOL_ADDRESS=${{ vars.POOL_ADDRESS }} \
-              -e WEB_ADDRESS=localhost:8082 \
+              -e WEB_ADDRESS=localhost:8080 \
               -e WALLET_PRIVATE_KEY=${{ secrets.WALLET_PRIVATE_KEY }} \
-              -p 8082:8082 \
+              -p 8080:8080 \
               --name proxy-router-test \
               $BUILDIMAGE:$BUILDTAG || (echo "❌ Failed to start image with tag: $BUILDIMAGE:$BUILDTAG" && exit 1)
             echo "✅ Proxy-Router $BUILDIMAGE:$BUILDTAG started successfully!"
-            curl localhost:8888/healthcheck || (echo "❌ Failed to fetch healthcheck" && exit 0)
+            curl -s http://localhost:8080/healthcheck || (echo "❌ Failed to fetch healthcheck" && exit 0)
 
             timeout=10
-            while ! curl -s localhost:8082/healthcheck >/dev/null; do
+            while ! curl -s http://localhost:8080/healthcheck >/dev/null; do
               ((timeout--))
               if ((timeout <= 0)); then
                 echo "📜 Fetching container logs:"
@@ -139,7 +139,7 @@ jobs:
             done
             echo "✅ Proxy-Router $BUILDIMAGE:$BUILDTAG started successfully!"
 
-            VERSION_TAG=$(curl --silent http://localhost:8082/healthcheck | jq -r '.version')
+            VERSION_TAG=$(curl -s http://localhost:8080/healthcheck | jq -r '.version')
             echo "📜 Fetching container logs:"
             docker logs proxy-router-test
             if [ "$VERSION_TAG" == "$BUILDTAG" ]; then
